---
name: 'build images'
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['5.5.1']
        service: ['zookeeper', 'kafka']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare
        id: prep
        run: |
          SERVICE=${{ matrix.service }}
          VERSION=${{ matrix.version }}

          github_build='true' ./build.sh $SERVICE $VERSION

          TAGS="ghcr.io/honeycombio/${SERVICE}:${VERSION}"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=service::${SERVICE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ${{ steps.prep.outputs.service }}/Dockerfile
          # so it uses the local fs and not the git context (https://github.com/docker/build-push-action/#usage)
          context: ${{ steps.prep.outputs.service }}/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
